import { createPostgresSchedulingStore, listPayrollReports } from "@aquarela/application";
import {
  DataTable,
  type DataTableColumn,
  EmptyState,
  InfoTip,
  PageHeader,
  SectionCard,
  StatusPill,
  formatNumber,
  spacing,
} from "@aquarela/ui";
import { redirect } from "next/navigation";

import { getAuthStore } from "../../../../lib/auth";
import { getDb } from "../../../../lib/db";
import { resolveOrganization } from "../../../../lib/organization";
import { getServerSession } from "../../../../lib/server-session";
import {
  isWorkforceAuthorized,
  loadWorkforceAccess,
  PAYROLL_REPORT_READ_ROLES,
  PAYROLL_REPORT_WRITE_ROLES,
} from "../../../api/v1/workforce/access";
import {
  formatInstant,
  monthEndUtcDay,
  monthStartUtcDay,
  payrollStatusView,
  todayUtcDay,
} from "../workforce-labels";
import { GeneratePayrollReportModal } from "./generate-payroll-report-form";

export const dynamic = "force-dynamic";
export const metadata = { title: "Payroll reports — Aquarela Business Control" };

/** The register shows a bounded working set; the read API pages beyond it. */
const PAGE_LIMIT = 100;

const contentColumn = {
  display: "flex",
  flexDirection: "column",
  gap: spacing[6],
  maxWidth: 1120,
  margin: "0 auto",
  padding: `${spacing[8]}px ${spacing[4]}px`,
} as const;

/** Tables scroll inside a labelled region; the page never scrolls sideways. */
const tableWrap = { overflowX: "auto", minWidth: 0 } as const;

/**
 * The payroll-input report register (`WF-005`, `DEC-104`): the list and the
 * header action that opens the generate modal, linking to each report's detail.
 *
 * Reads the same application service and row shape as
 * `GET /api/v1/workforce/payroll-reports`. Access is the `Payroll-input
 * reports` matrix row (owner, general_manager, finance, admin —
 * `location_manager` is deliberately excluded, matrix None, and `analyst`'s
 * "Aggregate" grant is not implemented, so access fails closed).
 */
export default async function PayrollReportsPage() {
  const session = await getServerSession();
  if (session === undefined) {
    redirect("/login");
  }

  const access = await loadWorkforceAccess(session.userId);
  if (!isWorkforceAuthorized(access, PAYROLL_REPORT_READ_ROLES)) {
    return (
      <div style={contentColumn}>
        <PageHeader
          title="Payroll reports"
          scope="Workforce"
          description="The monthly payroll-input reports."
        />
        <EmptyState title="Not available for your role">
          Payroll-input reports are limited to owner, general manager, finance and admin. The
          location manager is deliberately excluded (matrix None) even though the worked-hours
          report grants it, and analyst's aggregate grant is not implemented — access fails closed.
        </EmptyState>
      </div>
    );
  }

  const organizationId = resolveOrganization();
  const reports = await listPayrollReports(createPostgresSchedulingStore(getDb().db), {
    organizationId,
    limit: PAGE_LIMIT,
  });

  const actorIds = [
    ...new Set(
      reports.flatMap((report) => (report.generatedBy === null ? [] : [report.generatedBy])),
    ),
  ];
  const actors = await Promise.all(actorIds.map((id) => getAuthStore().findUserById(id)));
  const actorLabelById = new Map(
    actorIds.map((id, index) => {
      const actor = actors[index];
      return [id, actor === undefined ? id : (actor.email ?? actor.username ?? id)] as const;
    }),
  );

  const canWrite = isWorkforceAuthorized(access, PAYROLL_REPORT_WRITE_ROLES);
  const today = todayUtcDay();

  const columns: readonly DataTableColumn[] = [
    { key: "period", header: "Period" },
    { key: "status", header: "Status" },
    { key: "generated", header: "Generated" },
    { key: "generatedBy", header: "Generated by" },
    { key: "exportFile", header: "Export file" },
  ];

  return (
    <div style={contentColumn}>
      <PageHeader
        title="Payroll reports"
        scope="Workforce"
        description="The frozen monthly payroll-input report for the accountant: per-employee hours, base rate and expected pay."
        actions={
          canWrite ? (
            <GeneratePayrollReportModal
              defaultPeriodStart={monthStartUtcDay(today)}
              defaultPeriodEnd={monthEndUtcDay(today)}
            />
          ) : undefined
        }
      />

      <SectionCard
        title="Reports"
        meta={
          <>
            {formatNumber(String(reports.length), { decimals: 0 })}{" "}
            {reports.length === 1 ? "report" : "reports"} · newest period first
            <InfoTip
              content="Only shifts in state assigned or completed count, so a report generated before month-end under-counts the period. Generate after month-end, or regenerate once the remaining shifts are completed."
              label="Why a pre-month-end report under-counts"
            />
          </>
        }
      >
        {reports.length === 0 ? (
          <EmptyState variant="plain" title="No payroll reports yet">
            {canWrite
              ? "Generate one for a month from the button above. A report freezes each employee's hours × base hourly rate for the period."
              : "No report has been generated for a period yet."}
          </EmptyState>
        ) : (
          <div style={tableWrap}>
            <DataTable
              caption="Payroll-input reports by period with status, generation facts and export state"
              columns={columns}
              rowHref={(row) => `/workforce/payroll-reports/${String(row.id)}`}
              rows={reports.map((report) => ({
                id: report.id,
                period: `${report.periodStart} → ${report.periodEnd}`,
                status: (
                  <StatusPill tone={payrollStatusView(report.status).tone}>
                    {payrollStatusView(report.status).label}
                  </StatusPill>
                ),
                generated: formatInstant(report.generatedAt),
                generatedBy:
                  report.generatedBy === null
                    ? "—"
                    : (actorLabelById.get(report.generatedBy) ?? report.generatedBy),
                exportFile:
                  report.exportFileId === null
                    ? "Not available (metadata only)"
                    : report.exportFileId,
              }))}
            />
          </div>
        )}
      </SectionCard>
    </div>
  );
}
