-- TOTP replay protection: persist the highest consumed RFC 6238 counter so
-- `verifyTotp` can reject a reused window. Generated by drizzle-kit (do not
-- hand-edit beyond this header).
--
-- Down path: ALTER TABLE "user_totp" DROP COLUMN "last_used_counter"; (the
-- check constraint drops with the column).
ALTER TABLE "user_totp" ADD COLUMN "last_used_counter" integer;--> statement-breakpoint
ALTER TABLE "user_totp" ADD CONSTRAINT "user_totp_last_used_counter_check" CHECK ("user_totp"."last_used_counter" is null or "user_totp"."last_used_counter" >= 0);